"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
import os
from . import config
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR + '/apps') # Add apps folder to sys.path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.DEBUG

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'django_filters',
    'drf_yasg', # API documentation
    'corsheaders',
    'django_celery_beat',
    'constance',
    'constance.backends.database',
    'explorer',
    
    # Local apps
    'core', # Core app
    #'account', # User management
    #'address', # Address management
    #'analytics', # Analytics
    #'basket', # Basket management
    #'catalog', # Product management
    #'finance', # Finance management
    #'inventory', # Inventory management
    #'invoice', # Invoice management
    #'notifications', # Notification management
    #'orders', # Order management
    #'payment', # Payment management
    #'promotions', # Discount/voucher management
    #'ratings', # Rating management
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config.POSTGRES_DB,
        'USER': config.POSTGRES_USER,
        'PASSWORD': config.POSTGRES_PASSWORD,
        'HOST': config.POSTGRES_SERVER,
        'PORT': config.POSTGRES_PORT,
    },
    'replica': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config.REPLICA_POSTGRES_SERVER,
        'USER': config.REPLICA_POSTGRES_USER,
        'PASSWORD': config.REPLICA_POSTGRES_PASSWORD,
        'HOST': config.REPLICA_POSTGRES_SERVER,
        'PORT': config.REPLICA_POSTGRES_PORT,
    }
}

# Explorer settings
EXPLORER_CONNECTIONS = {"Default": "replica"}
EXPLORER_DEFAULT_CONNECTION = "replica"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr'
TIME_ZONE = "Europe/Istanbul"
USE_I18N = True
#USE_L10N = True
USE_TZ = True

# Localization
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGES = [
    ('en', _('English')),
    ('tr', _('Turkish')),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CONSTANCE settings
CONSTANCE_BACKEND = "constance.backends.redisd.RedisBackend"
CONSTANCE_REDIS_CONNECTION = {
    "host": config.REDIS_SERVER,
    "port": config.REDIS_PORT,
    "db": config.REDIS_CONSTANCE_DB,
    "password": config.REDIS_PASSWORD,
}
from backend.constance_config import *


# CACHE settings
CACHES = {
    "default": {
        "BACKEND": config.REDIS_BACKEND,
        "LOCATION": f"redis://{config.REDIS_SERVER}:{config.REDIS_PORT}/{config.REDIS_CACHE_DB}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": f"{config.REDIS_PASSWORD}",
            "SOCKET_CONNECT_TIMEOUT": int(
                config.REDIS_CONNECT_TIMEOUT
            ),  # in seconds
            "SOCKET_TIMEOUT": int(config.REDIS_SOCKET_TIMEOUT),  # in seconds
        },
    }
}


# CELERY settings
CELERY_BROKER_URL = config.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = config.CELERY_RESULT_BACKEND

# SMTP settings
EMAIL_USE_TLS = config.EMAIL_USE_TLS
EMAIL_BACKEND = config.EMAIL_BACKEND
EMAIL_HOST = config.EMAIL_HOST
EMAIL_HOST_USER = config.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = config.EMAIL_HOST_PASSWORD
EMAIL_PORT = config.EMAIL_PORT

# Logging settings
if config.SHOW_DJANGO_LOG:
    import logging.config

    LOGGING_CONFIG = None

    # Get loglevel from env
    LOGLEVEL = config.LOGGING_LOG_LEVEL

    logging.config.dictConfig(
        {
            "version": 1,
            "disable_existing_loggers": False,
            "formatters": {
                "console": {
                    "format": "%(asctime)s %(levelname)s %(message)s",
                },
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "formatter": "console",
                },
            },
            "loggers": {
                "": {
                    "level": LOGLEVEL,
                    "handlers": [
                        "console",
                    ],
                },
            },
        }
    )

# Sentry settings
import sentry_sdk
sentry_sdk.init(
    dsn=config.SENTRY_DSN,
    environment=config.SENTRY_ENVIRONMENT,
)

#AWS S3 settings
AWS_ACCESS_KEY_ID = config.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = config.AWS_SECRET_ACCESS_KEY
AWS_S3_REGION = config.AWS_S3_REGION
AWS_ENDPOINT = f"s3.{AWS_S3_REGION}.amazonaws.com"
AWS_S3_BUCKET_NAME = config.AWS_S3_BUCKET_NAME
AWS_S3_CUSTOM_DOMAIN = f"https://{AWS_S3_BUCKET_NAME}.{AWS_ENDPOINT}"
IMAGE_URL = config.IMAGE_URL

# Rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ], # API uç noktalarına erişim yetkilendirmesini belirler.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ], # API uç noktalarına erişim izinlerini belirler.
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ], # Gelen verilerin nasıl işleneceğini belirler.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination', # Sayfalama için kullanılır.
    'PAGE_SIZE': 10, # Sayfalama için kullanılır.
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ], # Filtreleme ve sıralama için kullanılır.
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.SwaggerAutoSchema', # Otomatik API belgeleri için kullanılır. API uç noktalarının otomatik olarak belgelenmesini sağlar (ör. Swagger/OpenAPI).
    
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
    
    # TODO: API throttling -> Secondary stage
}

# API DOCUMENTATION settings
SWAGGER_SETTINGS = {
    'DEFAULT_INFO': 'backend.urls.schema_view',  # Varsayılan şema bilgisi. (örn: `openapi.Info` bilgilerini içerir)
    'SECURITY_DEFINITIONS': {  # Yetkilendirme bilgilerini ayarlar (örn: JWT token kullanımı için)
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': True,  # Session Authentication kullanımı
    'LOGIN_URL': 'rest_framework:login',  # Login için URL
    'LOGOUT_URL': 'rest_framework:logout',  # Logout için URL
    'DOC_EXPANSION': 'none',  # Swagger'da doküman görünümü (none, list veya full)
    'APIS_SORTER': 'alpha',  # API sıralama yöntemi (alpha veya method)
    'OPERATIONS_SORTER': 'alpha',  # Operasyon sıralama yöntemi
    'DEFAULT_MODEL_RENDERING': 'example',  # Model veri örneği (example veya schema)
    'SHOW_REQUEST_HEADERS': True,  # Request header’larını gösterme
    'VALIDATOR_URL': None,  # Swagger doğrulayıcı URL
}


REDOC_SETTINGS = {
    'LAZY_RENDERING': True,  # Yalnızca görünümde olan API bölümlerini render eder, performansı artırır.
    'PATH_IN_MIDDLE_PANEL': True,  # URL yolunu Redoc arayüzünde ortada gösterir.
    'NATIVE_SCROLLBARS': False,  # Redoc'ta tarayıcının varsayılan kaydırma çubuklarını kullanır.
    'EXPAND_RESPONSES': ['200', '201'],  # Belirtilen yanıt kodlarını varsayılan olarak genişletir.
}