# Generated by Django 5.1.2 on 2024-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('native_name', models.CharField(max_length=32, verbose_name='Native Name')),
                ('flag', models.CharField(help_text='Flag Url, example: https://restcountries.eu/data/tur.svg', max_length=512, verbose_name='Flag')),
                ('iso639_1', models.CharField(max_length=2, verbose_name='ISO639_1')),
                ('iso639_2', models.CharField(max_length=3, verbose_name='ISO639_2')),
                ('is_system_language', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
